# Default user and password
default_user = guest
default_pass = guest

# Management plugin
management.tcp.port = 15672

# Limits
disk_free_limit.absolute = 2GB
vm_memory_high_watermark.relative = 0.7

# Connection limits
channel_max = 2000